from fastapi import APIRouter, Response
import pandas as pd
from io import StringIO, BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from typing import List, Dict

router = APIRouter(prefix="/api/reports")

# In-memory storage for real-time reporting events
report_data: List[Dict] = [
    {"Provider": "AWS", "Resource": "S3-Prod-Backup", "Violation": "Versioning Disabled", "Status": "MEDIUM"},
    {"Provider": "GCP", "Resource": "IAM Policy", "Violation": "New Owner Detected", "Status": "HIGH"},
]

@router.get("/security-status")
async def get_security_status_report():
    """Proxy for the main security audit PDF."""
    return await export_pdf()

@router.get("/csv")
async def export_csv():
    # Uses the global real-time report_data
    df = pd.DataFrame(report_data)
    output = StringIO()
    df.to_csv(output, index=False)
    return Response(
        content=output.getvalue(),
        media_type="text/csv",
        headers={"Content-Disposition": "attachment; filename=CloudGuard_Audit.csv"}
    )

@router.get("/pdf")
async def export_pdf():
    from app.db.database import get_recent_scans
    scans = get_recent_scans(limit=1)
    latest_scan = scans[0] if scans else None
    
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    
    # Header
    p.setFont("Helvetica-Bold", 28)
    p.setFillColorRGB(0.1, 0.4, 0.8) 
    p.drawString(50, 750, "CloudGuard AI Enterprise")
    
    p.setFont("Helvetica-Bold", 16)
    p.setFillColorRGB(0.2, 0.2, 0.2)
    p.drawString(50, 725, "Continuous Security Audit Report")
    
    timestamp = latest_scan["timestamp"] if latest_scan else pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
    p.setFont("Helvetica", 10)
    p.drawString(50, 710, f"Audit Date: {timestamp}")
    p.line(50, 700, 550, 700)
    
    # Summary
    p.setFont("Helvetica-Bold", 14)
    p.drawString(50, 670, "1. Posture Summary")
    p.setFont("Helvetica", 11)
    score = latest_scan["risk_score"] if latest_scan else "--"
    p.drawString(50, 650, f"Aggregate Risk Score: {score}/100")
    p.drawString(50, 635, f"Cloud Provider: {latest_scan['provider'].upper() if latest_scan else 'MULTI-CLOUD'}")

    # Findings
    p.setFont("Helvetica-Bold", 14)
    p.drawString(50, 600, "2. Top Security Findings")
    
    y = 570
    p.setFont("Helvetica", 10)
    if latest_scan and latest_scan["findings"]:
        for f in latest_scan["findings"][:10]:
            p.setFillColorRGB(0.8, 0, 0) if f["severity"] == "CRITICAL" else p.setFillColorRGB(0.8, 0.4, 0)
            p.drawString(50, y, f"[{f['severity']}] {f['name']}")
            y -= 20
    else:
        p.drawString(50, y, "No active high-priority findings detected.")
        y -= 20
        
    p.setFillColorRGB(0, 0, 0)
    p.line(50, y, 550, y)
    y -= 30
    
    p.setFont("Helvetica-Oblique", 10)
    p.drawString(50, y, "Generated by CloudGuard AI Enterprise Audit Engine.")

    p.showPage()
    p.save()
    
    return Response(
        content=buffer.getvalue(),
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=CloudGuard_Enterprise_Audit.pdf"}
    )
